### ISSUE TITLE
Can't read mod paths with mixed-case names

### ISSUE THREAD

**Issue by swizzlizard** [KiwifruitDev/SFM-Asset-Browser#1]
Apologies I'm new to bug reporting but this project is so cool, I wanna help out if I can.

Im having an issue where the browser is not reading custom mods.
![image](https://user-images.githubusercontent.com/49766241/212727134-6817e3d9-8f50-4e74-a74c-0feb7e786bac.png)
These mods as well as the others that come with sfm, like tf2, left4dead2, etc all are working as expected.
![image](https://user-images.githubusercontent.com/49766241/212728514-7645372b-ac59-4ace-8fef-0ca6d4eb15ab.png)
These mods however, all of which are custom made and functioning normally aside from the browser, dont load anything past the root folder.
Ive also tested all of the above individually and as a group.

**Comment by KiwifruitDev** [comment]
Thank you for the issue report!

In theory, it should just blindly read any directory that isn't explicitly blacklisted, even if they're not in the SFM search paths.

I released a new version on the workshop, mind trying it out? I'm not exactly sure what causes this, but it could have been fixed in the newest revision.

I'll investigate and try to replicate this when possible.

Hope this gets resolved.

**Comment by swizzlizard** [comment]
Issue persisting in new version, I don't know if this will help or not, but here's an example of the custom mod folder compared with the normal usermod. I don't know if a discrepancy in file structure would cause an issue or not.
![image](https://user-images.githubusercontent.com/49766241/212811008-12bea752-17e5-4b66-a319-7b6b3624ed96.png)

**Comment by KiwifruitDev** [comment]
Turns out that the issue stems from the mod path name being mixed case.

Currently working on fixing this issue for next commit.
